### ISSUE TITLE
Use `volumn` not work 

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [dockerfile/mysql#4]
Run command  not work
    docker run --name mysql -d -v /data/mysql:/var/lib/mysql dockerfile/mysql

```
Error: 
150311 07:36:04 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150311 07:36:04 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
```

What's solve it?

**Comment by BenNG** [comment]
Hello, if you can't wait for them to fix this issue you can consider using [that](https://github.com/BenNG/docker-mysql)

**Comment by feifeiiiiiiiiiii** [comment]
Hi @BenNG ,  are you sure the problem is a bug in `dockerfile/mysql`?

**Comment by BenNG** [comment]
Hummm ... try  /data/mysql:/var/lib/mysql instead of
/data/mysql:/var/log/mysql ?

2015-03-11 14:34 GMT+00:00 qinpengfei2008 notifications@github.com:

> Hi @BenNG https://github.com/BenNG , are you sure the problem is a bug
> in dockerfile/mysql?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dockerfile/mysql/issues/4#issuecomment-78274607.

## 

Cordialement,

_Benjamin NGUYEN_
_Développeur_
benjamin.nguyen@clicrdv.com

9 rue Maurice Mallet
92130 Issy-Les-Moulineaux
Téléphone : +33 (0)1 83 62 04 04
Télécopie : +33 (0)9 55 56 03 55
www.clicrdv.com

**Comment by feifeiiiiiiiiiii** [comment]
@BenNG  Sorry, I write command error, right command  is `docker run --name mysql -d -v /data/mysql:/var/lib/mysql dockerfile/mysql`, error occurred

```
150311 07:36:04 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
150311 07:36:04 mysqld_safe mysqld from pid file /var/run/mysqld/mysqld.pid ended
```

**Comment by BenNG** [comment]
ok so I don't know... post en stackoverflow you will have more answers

**Comment by feifeiiiiiiiiiii** [comment]
ok，thanks @BenNG
